[package]
name = "epic-authentik"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
reqwest = { version = "0.11", features = ["native-tls"] }
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.20"
